# L1: Language modelling

In this lab you will implement and train two neural language models: the fixed-window model and the recurrent neural network model. You will evaluate these models by computing their perplexity on a benchmark dataset.

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

For this lab, you should use the GPU if you have one:

In [2]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [3]:
print(torch.cuda.is_available())

True


## Data

The data for this lab is [WikiText](https://blog.einstein.ai/the-wikitext-long-term-dependency-language-modeling-dataset/), a collection of more than 100 million tokens extracted from the “Good” and “Featured” articles on Wikipedia. We will use the small version of the dataset, which contains slightly more than 2.5 million tokens.

The next cell contains code for an object that will act as a container for the “training” and the “validation” section of the data. We fill this container by reading the corresponding text files. The only processing we do is to whitespace-tokenise, and to enclose each non-empty line within `<bos>` (beginning-of-sentence) and `<eos>` (end-of-sentence) tokens.

In [4]:
class WikiText(object):
    
    def __init__(self):
        self.vocab = {}
        self.train = self.read_data('wiki.train.tokens')
        self.valid = self.read_data('wiki.valid.tokens')
    
    def read_data(self, path):
        ids = []
        with open(path, encoding='utf-8') as source:
            for line in source:
                line = line.rstrip()
                if line:
                    for token in ['<bos>'] + line.split() + ['<eos>']:
                        if token not in self.vocab:
                            self.vocab[token] = len(self.vocab)
                        ids.append(self.vocab[token])
        return ids

The cell below loads the data and prints the total number of tokens and the size of the vocabulary.

In [5]:
wikitext = WikiText()
print('Tokens in train:', len(wikitext.train))
print('Tokens in valid:', len(wikitext.valid))
print('Vocabulary size:', len(wikitext.vocab))

Tokens in train: 2099444
Tokens in valid: 218808
Vocabulary size: 33279


## Problem 1: Fixed-window model

In this section, you will implement and train the fixed-window neural language model proposed by [Bengio et al. (2003)](http://www.jmlr.org/papers/volume3/bengio03a/bengio03a.pdf) and presented in the lectures. Recall that an input to the network takes the form of a vector of $n-1$ integers representing the preceding words. Each integer is mapped to a vector via an embedding layer. (All positions share the same embedding.) The embedding vectors are then concatenated and sent through a two-layer feed-forward network with a non-linearity in the form of a rectified linear unit (ReLU) and a final softmax layer.

### Problem 1.1: Vectorise the data (1&nbsp;point)

Your first task is to write code for transforming the data in the WikiText container into a vectorised form that can be fed to the fixed-window model. Concretely, you will implement a [collate function](https://pytorch.org/docs/stable/data.html#dataloader-collate-fn) in the form of a callable vectoriser object. Complete the skeleton code in the cell below:

In [6]:
class FixedWindowVectorizer(object):
    def __init__(self, n):
        # n-gram order
        self.n = n

    def __call__(self, data):
        # TODO: Replace the following line with your own code
        N = len(data) - (self.n-1) # calculate how many n-grams in the dataset 

        X = [data[i:i+self.n-1] for i in range(N)]
        y = [data[i+self.n-1] for i in range(N) ]                               # [ , )
        return torch.tensor(X), torch.tensor(y)

Your code should implement the following specification:

**__init__** (*self*, *n*)

> Creates a new vectoriser with n-gram order $n$. Your code should be able to handle arbitrary n-gram orders $n \geq 1$.

**__call__** (*self*, *data*)

> Transforms WikiText *data* (a list of word ids) into a pair of tensors $\mathbf{X}$, $\mathbf{y}$ that can be used to train the fixed-window model. Let $N$ be the total number of $n$-grams from the token list; then $\mathbf{X}$ is a matrix with shape $(N, n-1)$ and $\mathbf{y}$ is a vector with length $N$.

#### 🤞 Test your code

Test your implementation by running the code in the next cell. Does the output match your expectation?

In [7]:
valid_x, valid_y = FixedWindowVectorizer(2)(wikitext.valid)

In [8]:
train_x, train_y = FixedWindowVectorizer(2)(wikitext.train)

### Problem 1.2: Implement the model (2&nbsp;points)

Your next task is to implement the fixed-window model based on the graphical specification given in the lecture.

In [11]:
class FixedWindowModel(nn.Module):

    def __init__(self, n, n_words, embedding_dim=50, hidden_dim=50):
        # n_words -- number of words in vocabulary
        # n       -- n-gram
        
        super().__init__()
        self.embedding = nn.Embedding(n_words,embedding_dim)
        self.fc = nn.Linear((n - 1) * embedding_dim, hidden_dim) 
        self.ReLU = nn.ReLU()
        self.out = nn.Linear(hidden_dim, n_words)   
        # TODO: Add your own code

    def forward(self, x):
        embeds = self.embedding(x)
        embeds = embeds.view(x.size(0), -1)
        hidden = self.fc(embeds)
        hidden = self.ReLU(hidden)
        output = self.out(hidden) # output is one-hot code for every word in vocablary
        probs = F.softmax(output, dim=1)        
        return output

Here is the specification of the two methods:

**__init__** (*self*, *n*, *n_words*, *embedding_dim*=50, *hidden_dim*=50)

> Creates a new fixed-window neural language model. The argument *n* specifies the model&rsquo;s $n$-gram order. The argument *n_words* is the number of words in the vocabulary. The arguments *embedding_dim* and *hidden_dim* specify the dimensionalities of the embedding layer and the hidden layer of the feedforward network, respectively; their default value is 50.

**forward** (*self*, *x*)

> Computes the network output on an input batch *x*. The shape of *x* is $(B, n-1)$, where $B$ is the batch size. The output of the forward pass is a tensor of shape $(B, V)$ where $V$ is the number of words in the vocabulary.

**Hint:** The most efficient way to implement the vector concatenation in this model is to use the [`view()`](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.view) method.

#### 🤞 Test your code

Test your code by instantiating the model and feeding it a batch of examples from the training data.

In [12]:
n_words = len(wikitext.vocab)  
model = FixedWindowModel(2, n_words)

batch_size = 5
train_x_batch = train_x[:batch_size]

output = model(train_x_batch)
print(output)

tensor([[ 0.0043, -0.1411,  0.1287,  ..., -0.0634,  0.0798,  0.0381],
        [ 0.2523,  0.0688,  0.2223,  ..., -0.0818,  0.3047,  0.5258],
        [-0.1861,  0.2528,  0.0870,  ..., -0.2823, -0.0673,  0.0491],
        [-0.5386, -0.3678, -0.7150,  ..., -0.3137,  0.4225,  0.0059],
        [ 0.1723,  0.2063,  0.0388,  ..., -0.0166,  0.1142, -0.0798]],
       grad_fn=<AddmmBackward0>)


### Problem 1.3: Train the model (3&nbsp;points)

Your final task is to write code to train the fixed-window model using minibatch gradient descent and the cross-entropy loss function. This should be a straightforward generalisation of the training loops that you have seen so far. Complete the skeleton code in the cell below:

In [13]:
def get_batches(data, batch_size):
    for i in range(0, len(data) - batch_size + 1, batch_size):
        yield data[i:i + batch_size]

In [14]:
def train_fixed_window(n, n_epochs=2, batch_size=3200, lr=0.01):
    n_words = len(wikitext.vocab)
    model = FixedWindowModel(n, n_words)
    optimizer = optim.Adam(model.parameters(), lr=lr)
    total_loss = 0

    for epoch in range(n_epochs):
        model.train()  # 设置模型为训练模式
        for batch_x, batch_y in zip(get_batches(train_x, batch_size), get_batches(train_y, batch_size)):
            # batch_x 和 batch_y 是配对的输入和目标

            # 清空梯度
            optimizer.zero_grad()

            # 前向传播
            outputs = model(batch_x)
            
            # 计算损失
            loss = F.cross_entropy(outputs, batch_y)
            print("train_loss: ",loss)
            # 反向传播和优化
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
            
    train_loss = total_loss/len(train_x)

    model.eval()
    total_loss = 0
    with torch.no_grad():
        for batch_x,batch_y in zip(get_batches(valid_x, batch_size), get_batches(valid_y, batch_size)):
            batch_y = torch.tensor(batch_y, dtype=torch.long)
            outputs = model(batch_x)
            total_loss += F.cross_entropy(outputs, batch_y, reduction='sum').item()

        # 计算验证集上的平均损失
    valid_loss = total_loss / len(valid_x)
    perplexity = torch.exp(torch.tensor(valid_loss))

    print(f'Epoch {epoch+1}, Train Loss: {train_loss}, Validation Perplexity: {perplexity}') 

    return model


Here is the specification of the training function:

**train_fixed_window** (*n*, *n_epochs* = 1, *batch_size* = 3200, *lr* = 0.01)

> Trains a fixed-window neural language model of order *n* using minibatch gradient descent and returns it. The parameters *n_epochs* and *batch_size* specify the number of training epochs and the minibatch size, respectively. Training uses the cross-entropy loss function and the [Adam optimizer](https://pytorch.org/docs/stable/optim.html#torch.optim.Adam) with learning rate *lr*. After each epoch, prints the perplexity of the model on the validation data.

The code in the cell below trains a bigram model.

In [15]:
model_fixed_window = train_fixed_window(2)

train_loss:  tensor(10.4342, grad_fn=<NllLossBackward0>)
train_loss:  tensor(10.2747, grad_fn=<NllLossBackward0>)
train_loss:  tensor(10.1096, grad_fn=<NllLossBackward0>)
train_loss:  tensor(9.9067, grad_fn=<NllLossBackward0>)
train_loss:  tensor(9.7315, grad_fn=<NllLossBackward0>)
train_loss:  tensor(9.3465, grad_fn=<NllLossBackward0>)
train_loss:  tensor(9.2265, grad_fn=<NllLossBackward0>)
train_loss:  tensor(8.9221, grad_fn=<NllLossBackward0>)
train_loss:  tensor(8.5131, grad_fn=<NllLossBackward0>)
train_loss:  tensor(8.3963, grad_fn=<NllLossBackward0>)
train_loss:  tensor(8.0415, grad_fn=<NllLossBackward0>)
train_loss:  tensor(7.8691, grad_fn=<NllLossBackward0>)
train_loss:  tensor(7.8227, grad_fn=<NllLossBackward0>)
train_loss:  tensor(7.7787, grad_fn=<NllLossBackward0>)
train_loss:  tensor(7.7726, grad_fn=<NllLossBackward0>)
train_loss:  tensor(7.5043, grad_fn=<NllLossBackward0>)
train_loss:  tensor(7.5083, grad_fn=<NllLossBackward0>)
train_loss:  tensor(7.4016, grad_fn=<NllLossB

C:\Users\17456\AppData\Local\Temp\ipykernel_6272\3417508707.py:32: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  batch_y = torch.tensor(batch_y, dtype=torch.long)


Epoch 2, Train Loss: 0.003864533742875154, Validation Perplexity: 336.4918518066406


#### Performance goal

**Your submitted notebook must contain output demonstrating a validation perplexity of at most 350.** If you do not reach this perplexity after the first epoch, try training for a second epoch.

⚠️ Computing the validation perplexity in one go (for the full validation set) will probably exhaust your computer’s memory and/or take a lot of time. If you run into this problem, do the computation at the minibatch level and aggregate the results.

#### 🤞 Test your code

To see whether your network is learning something, print or plot the loss and/or the perplexity on the training data. If the two values do not decrease during training, try to find the problem before wasting time (and electricity) on useless computation.

Training and even evaluation will take some time – on a CPU, you should expect several minutes per epoch, depending on hardware. Our reference implementation uses a GPU and runs in less than 30 seconds per epoch on [Colab](http://colab.research.google.com).

## Problem 2: Recurrent neural network model

In this section, you will implement the recurrent neural network language model. Recall that an input to this model is a vector of word ids. Each integer is mapped to an embedding vector. The sequence of embedded vectors is then fed into an unrolled LSTM. At each position $i$ in the sequence, the hidden state of the LSTM at that position is sent through a linear transformation into a final softmax layer representing the probability distribution over the words at position $i+1$. In theory, the input vector could represent the complete training data; for practical reasons, however, we will truncate the input to some fixed value *bptt_len*. This length is called the **backpropagation-through-time horizon**.

### Problem 2.1: Vectorise the data (1&nbsp;point)

As in the previous problem, your first task is to transform the data in the WikiText container into a vectorised form that can be fed to the model.

In [16]:
class RNNVectorizer(object):
    def __init__(self, bptt_len):
        # backpropagation-through-time horizon
        self.bptt_len = bptt_len

    def __call__(self, data):
        # TODO: Replace the following line with your own code
        num_sequences = len(data) // self.bptt_len

        # Initialize X and Y tensors
        X = torch.zeros((num_sequences, self.bptt_len), dtype=torch.long)
        Y = torch.zeros((num_sequences, self.bptt_len), dtype=torch.long)

        for i in range(num_sequences):
            start_idx = i * self.bptt_len
            end_idx = start_idx + self.bptt_len

            # Populate X with the current sequence
            X[i] = torch.tensor(data[start_idx:end_idx])

            # Populate Y with the sequence offset by one position
            Y[i] = torch.tensor(data[start_idx + 1:end_idx + 1] if end_idx < len(data) else data[start_idx + 1:] + [0])

        return X, Y

Your vectoriser should meet the following specification:

**__init__** (*self*, *bptt_len*)

> Creates a new vectoriser. The parameter *bptt_len* specifies the backpropagation-through-time horizon.

**__call__** (*self*, *data*)

> Transforms a list of token indexes *data* into a pair of tensors $\mathbf{X}$, $\mathbf{Y}$ that can be used to train the recurrent neural language model. The rows of both tensors represent contiguous subsequences of token indexes of length *bptt_len*. Compared to the sequences in $\mathbf{X}$, the corresponding sequences in $\mathbf{Y}$ are shifted one position to the right. More precisely, if the $i$th row of $\mathbf{X}$ is the sequence that starts at token position $j$, then the same row of $\mathbf{Y}$ is the sequence that starts at position $j+1$.

#### 🤞 Test your code

Test your implementation by running the following code:

In [17]:
valid_x, valid_y = RNNVectorizer(32)(wikitext.valid)

print(valid_x.size(), valid_y.size())

torch.Size([6837, 32]) torch.Size([6837, 32])


In [18]:
train_x, train_y = RNNVectorizer(32)(wikitext.train)

In [19]:
train_x[0]

tensor([ 0,  1,  2,  3,  4,  1,  5,  0,  6,  7,  2,  8,  9, 10,  3, 11, 12,  9,
        13, 14, 15, 16,  2, 17, 18, 19,  8, 20, 14, 21, 22, 23])

In [10]:
print(train_y[0])

tensor([ 1,  2,  3,  4,  1,  5,  0,  6,  7,  2,  8,  9, 10,  3, 11, 12,  9, 13,
        14, 15, 16,  2, 17, 18, 19,  8, 20, 14, 21, 22, 23, 24])


### Problem 2.2: Implement the model (2&nbsp;points)

Your next task is to implement the recurrent neural network model based on the graphical specification.

In [11]:
class RNNModel(nn.Module):

    def __init__(self, n_words, embedding_dim=50, hidden_dim=50):
        super().__init__()
        self.embedding = nn.Embedding(n_words, embedding_dim)
        #nn.init.normal_(self.embedding.weight, mean=0, std=0.01)
        #nn.init.xavier_normal_(self.embedding.weight)
        self.LSTM = nn.LSTM(embedding_dim, hidden_dim, batch_first = True)
        self.fc = nn.Linear(hidden_dim, n_words)




    def forward(self, x):
        # TODO: Replace the next line with your own code
        x = self.embedding(x)
        lstm_out, _ = self.LSTM(x)
        out = self.fc(lstm_out)
        return out

Your implementation should follow this specification:

**__init__** (*self*, *n_words*, *embedding_dim* = 50, *hidden_dim* = 50)

> Creates a new recurrent neural network language model based on an LSTM. The argument *n_words* is the number of words in the vocabulary. The arguments *embedding_dim* and *hidden_dim* specify the dimensionalities of the embedding layer and the LSTM hidden layer, respectively; their default value is 50.

**forward** (*self*, *x*)

> Computes the network output on an input batch *x*. The shape of *x* is $(B, H)$, where $B$ is the batch size and $H$ is the length of each input sequence. The shape of the output tensor is $(B, H, V)$, where $V$ is the size of the vocabulary.

#### 🤞 Test your code

Test your code by instantiating the model and feeding it a batch of examples from the training data.

In [12]:
print(valid_x[0])
model = RNNModel(n_words=len(wikitext.vocab))
output = model(valid_x[0])
print(output)

tensor([    0,     1, 32967, 32968,     1,     5,     0, 32967, 32968,    14,
          407,    24,    18,  6254, 19903,   311,  1445, 19903,    14,    27,
           28,  2577,    17,    10, 19903,   116,    18,  4930,  4122,  9612,
           14,  4855])
tensor([[-0.1278,  0.1540, -0.1164,  ..., -0.1109, -0.0335,  0.0066],
        [-0.1460,  0.1070, -0.1035,  ..., -0.0228, -0.0723, -0.0985],
        [-0.0490,  0.0793, -0.1817,  ..., -0.0906,  0.0745, -0.1262],
        ...,
        [-0.1130,  0.2508, -0.2141,  ..., -0.0333,  0.1696, -0.0889],
        [-0.2479,  0.1773, -0.0813,  ...,  0.0078,  0.1846, -0.0999],
        [-0.1508,  0.0464, -0.1393,  ..., -0.0494,  0.0285, -0.0111]],
       grad_fn=<AddmmBackward0>)


### Problem 2.3: Train the model (3&nbsp;points)

The training loop for the recurrent neural network model is essentially identical to the loop that you wrote for the feed-forward model. The only thing to note is that the cross-entropy loss function expects its input to be a two-dimensional tensor; you will therefore have to re-shape the output tensor from the LSTM as well as the gold-standard output tensor in a suitable way. The most efficient way to do so is to use the [`view()`](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.view) method.

In [13]:
train_x

tensor([[    0,     1,     2,  ...,    21,    22,    23],
        [   24,     2,     3,  ...,    44,    26,    14],
        [   47,    27,    18,  ...,    23,    18,    60],
        ...,
        [  349,     7,   428,  ...,   285, 23961,    27],
        [  495,   490,   152,  ...,  4855,  2491,    16],
        [   84,  9617,    27,  ...,   565,  1363,   152]])

In [14]:
import torch
import torch.nn as nn
import torch.optim as optim

def get_batches(data, batch_size):
    for i in range(0, len(data) - batch_size + 1, batch_size):
        yield data[i:i + batch_size]


def train_rnn(n_epochs=1, batch_size=100, lr=0.01):
    # Initialize the model
    model = RNNModel(n_words=len(wikitext.vocab))
    optimizer = optim.Adam(model.parameters(), lr=lr)
    criterion = nn.CrossEntropyLoss()

    for epoch in range(n_epochs):
        model.train()
        total_loss = 0

        # Iterate over batches
        for batch_x, batch_y in zip(get_batches(train_x, batch_size), get_batches(train_y, batch_size)):
            optimizer.zero_grad()
            outputs = model(batch_x)

            # Reshape outputs and targets to fit CrossEntropyLoss expectations
            outputs = outputs.view(-1, outputs.shape[-1])
            batch_y = batch_y.view(-1)

            loss = criterion(outputs, batch_y) # why is better than F.cross_entropy
            print("train_loss: ", loss.item())

            loss.backward()
            optimizer.step()
            total_loss += loss.item()

        train_loss = total_loss * batch_size /len(train_x)

        model.eval()
        total_loss = 0
        with torch.no_grad():
            for batch_x, batch_y in zip(get_batches(valid_x, batch_size), get_batches(valid_y, batch_size)):
                batch_y = torch.tensor(batch_y, dtype=torch.long)
                outputs = model(batch_x)

                outputs = outputs.view(-1, outputs.shape[-1])
                batch_y = batch_y.view(-1)

                loss = criterion(outputs, batch_y) # why is better than F.cross_entropy

                total_loss += loss.item()

    valid_loss = total_loss * batch_size / len(valid_x)
    perplexity = torch.exp(torch.tensor(valid_loss))

    print(f'Epoch {epoch+1}, Train Loss: {train_loss}, Validation Perplexity: {perplexity}')


    return model


# Additional functions like 'create_batches' and 'calculate_perplexity' need to be defined.

Here is the specification of the training function:

**train_rnn** (*n_epochs* = 1, *batch_size* = 1000, *bptt_len* = 32, *lr* = 0.01)

> Trains a recurrent neural network language model on the WikiText data using minibatch gradient descent and returns it. The parameters *n_epochs* and *batch_size* specify the number of training epochs and the minibatch size, respectively. The parameter *bptt_len* specifies the length of the backpropagation-through-time horizon, that is, the length of the input and output sequences. Training uses the cross-entropy loss function and the [Adam optimizer](https://pytorch.org/docs/stable/optim.html#torch.optim.Adam) with learning rate *lr*. After each epoch, prints the perplexity of the model on the validation data.

Evaluate your model by running the following code cell:

In [15]:
model_rnn = train_rnn(batch_size=100, lr=0.01, n_epochs = 2)

train_loss:  10.419988632202148
train_loss:  10.367169380187988
train_loss:  10.286264419555664
train_loss:  10.170522689819336
train_loss:  9.953758239746094
train_loss:  9.403770446777344
train_loss:  9.008001327514648
train_loss:  8.457756996154785
train_loss:  7.991602897644043
train_loss:  7.9494948387146
train_loss:  7.667288303375244
train_loss:  7.611982345581055
train_loss:  7.6850152015686035
train_loss:  7.884538650512695
train_loss:  8.018348693847656
train_loss:  7.731550693511963
train_loss:  7.949888229370117
train_loss:  7.852181911468506
train_loss:  7.736701011657715
train_loss:  7.6605072021484375
train_loss:  7.801647186279297
train_loss:  7.785073280334473
train_loss:  7.921989917755127
train_loss:  7.819475173950195
train_loss:  7.5798115730285645
train_loss:  7.608362197875977
train_loss:  7.489190578460693
train_loss:  7.577753067016602
train_loss:  7.393876552581787
train_loss:  7.679196357727051
train_loss:  7.570830821990967
train_loss:  7.502748966217041
tra

C:\Users\17456\AppData\Local\Temp\ipykernel_26224\1643080265.py:42: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  batch_y = torch.tensor(batch_y, dtype=torch.long)


train_loss:  6.030330181121826
train_loss:  5.861627578735352
train_loss:  6.013350963592529
train_loss:  6.127972602844238
train_loss:  6.037977695465088
train_loss:  5.711465835571289
train_loss:  5.860497951507568
train_loss:  5.970273017883301
train_loss:  5.897275447845459
train_loss:  5.882673263549805
train_loss:  5.873165130615234
train_loss:  5.982775688171387
train_loss:  6.099665641784668
train_loss:  6.2073974609375
train_loss:  6.163914680480957
train_loss:  5.934309482574463
train_loss:  5.894278526306152
train_loss:  5.959204196929932
train_loss:  5.847671031951904
train_loss:  5.79086446762085
train_loss:  5.914404392242432
train_loss:  5.951840400695801
train_loss:  6.118196487426758
train_loss:  6.045746326446533
train_loss:  5.862207412719727
train_loss:  5.947079658508301
train_loss:  5.967791557312012
train_loss:  6.057098388671875
train_loss:  5.771705150604248
train_loss:  5.978606700897217
train_loss:  6.027604579925537
train_loss:  5.879590034484863
train_loss:

#### Performance goal

**Your submitted notebook must contain output demonstrating a validation perplexity of at most 280.** If you do not reach this perplexity after the first epoch, try training for a second epoch.

## Problem 3: Parameter initialisation (3&nbsp;points)

The error surfaces explored when training neural networks can be very complex. Because of this, it is important to choose “good” initial values for the parameters. In PyTorch, the weights of the embedding layer are initialised by sampling from the standard normal distribution $\mathcal{N}(0, 1)$. Test how changing the initialisation affects the perplexity of your feed-forward language model. Find research articles that propose different initialisation strategies.

Write a short (150&nbsp;words) report about your experiments and literature search. Use the following prompts:

* What different initialisation did you try? What results did you get?
* How do your results compare to what was suggested by the research articles?
* What did you learn? How, exactly, did you learn it? Why does this learning matter?

You are allowed to consult sources for this problem if you appropriately cite them. If in doubt, please read the [Academic Integrity Policy](https://www.ida.liu.se/~TDDE09/logistics/policies.html#academic-integrity-policy).



*At first we decided to try different values for the batch_size and lr parameters to find what was best suitable for this particular task. In the end we decided on a batch_size of 100 and a loss rate of 0.01. In the interest of time we only trained with one Epoch, even though it took us two Epochs to reach a perplexity better than 280. We will compare it to default settings with only one Epoch. *

Two articles regarding weight initialization were considered when testing different configurations. First, the paper “Understanding the difficulty of training deep feedforward neural networks” by Xavier Glorot and Yoshua Bengio inspired us to try to initialize our weights using the “xavier_normal” initialization that is part of the pytorch library.  The initialization gave a slight improvement in perplexity (314 vs 317) compared to the default weight initialization of pytorch.
We also found in the paper “An Exploration of Word Embedding Initialization
in Deep-Learning Tasks” by Tom Kocmi and Ondrej Bojar that a weight initialization using a normal distribution of N(0, 0.01) instead of N(0,1) did well when they were exploring weight initializations for NLP tasks. We tried this with torch.nn.init.normal_ in pytorch. In our case we got a higher perplexity score of about 330 vs 315.
What we can say from the experiments is that different weight initializations warrants different results and is likely another part one needs to consider when choosing your model.


Sources:

Glorot, X., & Bengio, Y. (2010, March). Understanding the difficulty of training deep feedforward neural networks. In Proceedings of the thirteenth international conference on artificial intelligence and statistics (pp. 249-256). JMLR Workshop and Conference Proceedings.

Kocmi, T., & Bojar, O. (2017). An exploration of word embedding initialization in deep-learning tasks. arXiv preprint arXiv:1711.09160.
